# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

matrix:
  #fast_finish: true
  include:
     - os: osx
      brew_packages: curl
      env: PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
    - os: osx
      brew_packages: curl-openssl
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/curl-openssl/lib/pkgconfig"
        - HTTPBIN_TEST_SERVER="https://nghttp2.org/httpbin"
  allow_failures:
    - r: devel
      os: osx

    - r: devel
      os: linux

cache: packages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

after_success:
  - Rscript -e 'covr::codecov()'
