# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

    - r: devel
      os: linux

cache: packages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

warnings_are_errors: false

#after_success:
#  - Rscript -e 'covr::code
