# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

    - r: devel
      os: linux

cache: packages

addons:
  homebrew:
    packages:
    - curl
    - curl-openssl

after_success:
  - Rscript -e 'covr::codecov()'
