# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

cache: packages
sudo: required
dist: trusty

warnings_are_errors: false

#after_success:
#  - Rscript -e 'covr::code
